[package]
name = "mir4scope-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convert_case = "0.6.0"
dotenv = "0.15.0"
mongodb = "2.8.2"
reqwest = { version = "0.11.26", features = ["json"] }
serde = "1.0.197"
serde_json = "1.0.114"
tokio = "1.36.0"
